import type { Word } from './word';
import type { Syllable } from './syllable';
import { Lyrics } from './lyrics';
import { createTime } from './time';

interface JsonSyllable {
  readonly reading: string;
  readonly time: number;
  readonly isSet: boolean;
}

interface JsonWord {
  readonly reading: string;
  readonly syllables: JsonSyllable[];
  readonly withRuby: boolean;
  readonly isReadingAutoGenerated: boolean;
}

interface JsonLyrics {
  readonly metadata: Record<string, string>;
  readonly words: JsonWord[];
}

function toJsonSyllable(syl: Syllable): JsonSyllable {
  return {
    reading: syl.reading,
    time: syl.time.msec,
    isSet: syl.isSet,
  };
}

function fromJsonSyllable(json: JsonSyllable): Syllable {
  return {
    reading: json.reading,
    time: createTime(json.time),
    isSet: json.isSet,
  };
}

export function toJsonWord(word: Word): JsonWord {
  return {
    reading: word.reading,
    syllables: word.syllables.map(toJsonSyllable),
    withRuby: word.withRuby,
    isReadingAutoGenerated: word.isReadingAutoGenerated,
  };
}

export function fromJsonWord(json: JsonWord): Word {
  return {
    reading: json.reading,
    syllables: json.syllables.map(fromJsonSyllable),
    withRuby: json.withRuby,
    isReadingAutoGenerated: json.isReadingAutoGenerated,
  };
}

export function toJson(lyrics: Lyrics, indent: number = 2): string {
  const json: JsonLyrics = {
    metadata: lyrics.metadata,
    words: lyrics.words.map(toJsonWord),
  };
  return JSON.stringify(json, null, indent > 0 ? indent : undefined);
}

export function fromJson(text: string): Lyrics {
  try {
    const parsed = JSON.parse(text) as Partial<JsonLyrics>;

    const metadata: Record<string, string> = {};
    if (parsed.metadata && typeof parsed.metadata === 'object') {
      Object.entries(parsed.metadata).forEach(([key, value]) => {
        metadata[key.toLowerCase()] = String(value);
      });
    }

    let words: Word[] = [];
    if (Array.isArray(parsed.words)) {
      words = parsed.words.map(fromJsonWord);
    }

    return new Lyrics(words, metadata);
  } catch {
    return new Lyrics();
  }
}
