import type { Word } from './word';
import type { Time } from './time';
import { isSeparatorWord, wordSyllableCount } from './word';
import { createTime } from './time';

export interface BeatRef {
  wordIndex: number;
  sylIndex: number;
}

export class Lyrics {
  words: Word[];

  metadata: Record<string, string>;

  globalOffsetMs: number = 0;

  constructor(words: Word[] = [], metadata: Record<string, string> = {}) {
    this.words = words;
    this.metadata = metadata;
  }

  getWords(): Word[] {
    return this.words;
  }

  getMetadata(): Record<string, string> {
    return this.metadata;
  }

  getGlobalOffset(): number {
    return this.globalOffsetMs;
  }

  wordCount(): number {
    return this.words.length;
  }

  syllableCount(): number {
    return this.words.reduce(
      (count, word) => count + wordSyllableCount(word),
      0,
    );
  }

  nonSeparatorSyllableCount(): number {
    return this.words.reduce((count, word) => {
      if (!isSeparatorWord(word)) {
        return count + wordSyllableCount(word);
      }
      return count;
    }, 0);
  }

  findWordByIndex(index: number): Word {
    return this.words[index];
  }

  getBeatRefs(): BeatRef[] {
    const refs: BeatRef[] = [];
    this.words.forEach((word, wordIndex) => {
      if (isSeparatorWord(word)) return;
      word.syllables.forEach((_, sylIndex) => {
        refs.push({ wordIndex, sylIndex });
      });
    });
    return refs;
  }

  getBeatCount(): number {
    return this.getBeatRefs().length;
  }

  getLineRanges(): Array<{ start: number; end: number }> {
    const ranges: Array<{ start: number; end: number }> = [];
    let start = 0;
    this.words.forEach((word, index) => {
      if (isSeparatorWord(word) && word.reading === '\n') {
        ranges.push({ start, end: index });
        start = index + 1;
      }
    });
    if (start < this.words.length) {
      ranges.push({ start, end: this.words.length });
    }
    return ranges;
  }

  getLineText(lineIndex: number): string {
    const ranges = this.getLineRanges();
    if (lineIndex < 0 || lineIndex >= ranges.length) return '';
    const { start, end } = ranges[lineIndex];
    const lineWords = this.words.slice(start, end);
    return lineWords.reduce((text, word) => {
      if (isSeparatorWord(word)) {
        if (word.reading === ' ') {
          return `${text} `;
        }
        return text;
      }
      return `${text}${word.reading}`;
    }, '');
  }

  appendWord(word: Word): void {
    this.words.push(word);
  }

  insertWord(index: number, word: Word): void {
    this.words.splice(index, 0, word);
  }

  removeWord(index: number): void {
    this.words.splice(index, 1);
  }

  replaceWord(index: number, word: Word): void {
    this.words[index] = word;
  }

  updateWordText(index: number, newText: string): void {
    const oldWord = this.words[index];
    if (isSeparatorWord(oldWord)) return;

    let newWord: Word;
    if (oldWord.isReadingAutoGenerated) {
      const firstSyl = oldWord.syllables[0];
      const newTime = firstSyl?.time ?? createTime(0);
      const newSyllable = {
        reading: newText,
        time: newTime,
        isSet: firstSyl?.isSet ?? false,
      };
      newWord = {
        ...oldWord,
        reading: newText,
        syllables: [newSyllable],
        withRuby: false,
      };
    } else {
      newWord = {
        ...oldWord,
        reading: newText,
      };
    }
    this.words[index] = newWord;
  }

  updateSyllableReading(
    wordIndex: number,
    sylIndex: number,
    newReading: string,
  ): void {
    const word = this.words[wordIndex];
    if (isSeparatorWord(word)) return;
    const newSyllables = [...word.syllables];
    newSyllables[sylIndex] = {
      ...newSyllables[sylIndex],
      reading: newReading,
    };
    this.words[wordIndex] = {
      ...word,
      syllables: newSyllables,
      withRuby: true,
      isReadingAutoGenerated: false,
    };
  }

  setSyllableTime(wordIndex: number, sylIndex: number, time: Time): void {
    const word = this.words[wordIndex];
    if (isSeparatorWord(word)) return;
    const newSyllables = [...word.syllables];
    newSyllables[sylIndex] = {
      ...newSyllables[sylIndex],
      time,
      isSet: true,
    };
    this.words[wordIndex] = {
      ...word,
      syllables: newSyllables,
    };
  }

  setGlobalOffset(offsetMs: number): void {
    this.globalOffsetMs = offsetMs;
  }

  setMetadata(key: string, value: string): void {
    this.metadata[key] = value;
  }

  validateTimeSequence(): boolean {
    const refs = this.getBeatRefs();
    let prevTime = -Infinity;
    return refs.every((ref) => {
      const syl = this.words[ref.wordIndex].syllables[ref.sylIndex];
      if (!syl.isSet) return true;
      if (syl.time.msec <= prevTime) return false;
      prevTime = syl.time.msec;
      return true;
    });
  }

  isFullyTimed(): boolean {
    const refs = this.getBeatRefs();
    return refs.every((ref) => {
      const syl = this.words[ref.wordIndex].syllables[ref.sylIndex];
      return syl.isSet;
    });
  }

  findUnsetBeats(): BeatRef[] {
    const refs = this.getBeatRefs();
    return refs.filter((ref) => {
      const syl = this.words[ref.wordIndex].syllables[ref.sylIndex];
      return !syl.isSet;
    });
  }
}
