import type { Syllable } from './syllable';
import type { Time } from './time';
import { createSyllable, createUnsetSyllable } from './syllable';

export interface Word {
  reading: string;
  syllables: Syllable[];
  withRuby: boolean;
  isReadingAutoGenerated: boolean;
}

export function createWord(reading: string, time: Time): Word {
  return {
    reading,
    syllables: [createSyllable(reading, time)],
    withRuby: false,
    isReadingAutoGenerated: true,
  };
}

export function createUnsetWord(reading: string): Word {
  return {
    reading,
    syllables: [createUnsetSyllable(reading)],
    withRuby: false,
    isReadingAutoGenerated: true,
  };
}

export function createWordWithSyllables(
  reading: string,
  syllables: Syllable[],
  withRuby: boolean,
  isReadingAutoGenerated: boolean,
): Word {
  if (syllables.length === 0) {
    return createUnsetWord(reading);
  }
  return {
    reading,
    syllables,
    withRuby,
    isReadingAutoGenerated,
  };
}

export function createSpaceWord(): Word {
  return {
    reading: ' ',
    syllables: [createUnsetSyllable(' ')],
    withRuby: false,
    isReadingAutoGenerated: true,
  };
}

export function createNewlineWord(): Word {
  return {
    reading: '\n',
    syllables: [createUnsetSyllable('\n')],
    withRuby: false,
    isReadingAutoGenerated: true,
  };
}

export function isSpaceWord(word: Word): boolean {
  return word.reading === ' ';
}

export function isNewlineWord(word: Word): boolean {
  return word.reading === '\n';
}

export function isSeparatorWord(word: Word): boolean {
  return isSpaceWord(word) || isNewlineWord(word);
}

export function wordStartTime(word: Word): Time {
  return word.syllables[0].time; // must have one syllable
}

export function wordSyllableCount(word: Word): number {
  return word.syllables.length;
}

export function wordFullySet(word: Word): boolean {
  return word.syllables.every((syl) => syl.isSet);
}

export function wordFullyUnset(word: Word): boolean {
  return word.syllables.every((syl) => !syl.isSet);
}
