import type { Lyrics } from '../../editor/lyrics';
import { isSeparatorWord, isSpaceWord, isNewlineWord } from '../../editor/word';
import {
  ContextMenuContainer,
  ContextMenuItem,
  ContextMenuSep,
} from '../../shared/components/ContextMenu';

interface ContextMenuProps {
  x: number;
  y: number;
  wordIndex: number;
  lyrics: Lyrics;
  onClose: () => void;
  onEditRuby: (wordIndex: number) => void;
  onEditText: (wordIndex: number) => void;
  onSplit: (wordIndex: number) => void;
  onDelete: (wordIndex: number) => void;
  onInsertBefore: (wordIndex: number) => void;
  onInsertAfter: (wordIndex: number) => void;
  onInsertSpace: (wordIndex: number) => void;
  onInsertNewline: (wordIndex: number) => void;
  onConvertToNormal?: (wordIndex: number) => void;
  onConvertToSpace?: (wordIndex: number) => void;
  onConvertToNewline?: (wordIndex: number) => void;
}

export default function ContextMenu({
  x,
  y,
  wordIndex,
  lyrics,
  onClose,
  onEditRuby,
  onEditText,
  onSplit,
  onDelete,
  onInsertBefore,
  onInsertAfter,
  onInsertSpace,
  onInsertNewline,
  onConvertToNormal,
  onConvertToSpace,
  onConvertToNewline,
}: ContextMenuProps) {
  const word = lyrics.words[wordIndex];
  const isSep = isSeparatorWord(word);
  const isSp = isSpaceWord(word);
  const isNl = isNewlineWord(word);
  const canSplit =
    !isSep && word.isReadingAutoGenerated && word.syllables.length === 1;

  const convertActions: { label: string; action: () => void }[] = [];
  if (isSp) {
    convertActions.push(
      { label: '转化为换行', action: () => onConvertToNewline?.(wordIndex) },
      {
        label: '转化为文字',
        action: () => {
          onEditText(wordIndex);
          onClose();
        },
      },
    );
  } else if (isNl) {
    convertActions.push(
      { label: '转化为空格', action: () => onConvertToSpace?.(wordIndex) },
      {
        label: '转化为文字',
        action: () => {
          onEditText(wordIndex);
          onClose();
        },
      },
    );
  }

  const insertActions = [
    { label: '在前面插入卡片', action: () => onInsertBefore(wordIndex) },
    { label: '在后面插入卡片', action: () => onInsertAfter(wordIndex) },
    { label: '插入空格', action: () => onInsertSpace(wordIndex) },
    { label: '插入换行', action: () => onInsertNewline(wordIndex) },
  ];

  return (
    <ContextMenuContainer x={x} y={y} onClose={onClose}>
      <ContextMenuItem
        onClick={() => {
          onEditRuby(wordIndex);
          onClose();
        }}
        disabled={isSep}
      >
        编辑注音
      </ContextMenuItem>
      <ContextMenuItem
        onClick={() => {
          onEditText(wordIndex);
          onClose();
        }}
      >
        编辑文字
      </ContextMenuItem>
      <ContextMenuItem
        onClick={() => {
          onSplit(wordIndex);
          onClose();
        }}
        disabled={!canSplit}
      >
        拆分
      </ContextMenuItem>
      <ContextMenuItem
        onClick={() => {
          onDelete(wordIndex);
          onClose();
        }}
      >
        删除
      </ContextMenuItem>
      {convertActions.length > 0 && <ContextMenuSep />}
      {convertActions.map((item) => (
        <ContextMenuItem
          key={item.label}
          onClick={() => {
            item.action();
            onClose();
          }}
        >
          {item.label}
        </ContextMenuItem>
      ))}
      <ContextMenuSep />
      {insertActions.map((item) => (
        <ContextMenuItem
          key={item.label}
          onClick={() => {
            item.action();
            onClose();
          }}
        >
          {item.label}
        </ContextMenuItem>
      ))}
    </ContextMenuContainer>
  );
}
