import { useRef } from 'react';
import { useClickOutside } from '../../shared/hooks/useClickOutside';
import type { Lyrics } from '../../editor/lyrics';
import { isSeparatorWord, isSpaceWord, isNewlineWord } from '../../editor/word';

interface ContextMenuProps {
  x: number;
  y: number;
  wordIndex: number;
  lyrics: Lyrics;
  onClose: () => void;
  onEditRuby: (wordIndex: number) => void;
  onEditText: (wordIndex: number) => void;
  onSplit: (wordIndex: number) => void;
  onDelete: (wordIndex: number) => void;
  onInsertBefore: (wordIndex: number) => void;
  onInsertAfter: (wordIndex: number) => void;
  onInsertSpace: (wordIndex: number) => void;
  onInsertNewline: (wordIndex: number) => void;
  onConvertToNormal?: (wordIndex: number) => void;
  onConvertToSpace?: (wordIndex: number) => void;
  onConvertToNewline?: (wordIndex: number) => void;
}

export default function ContextMenu({
  x,
  y,
  wordIndex,
  lyrics,
  onClose,
  onEditRuby,
  onEditText,
  onSplit,
  onDelete,
  onInsertBefore,
  onInsertAfter,
  onInsertSpace,
  onInsertNewline,
  onConvertToNormal,
  onConvertToSpace,
  onConvertToNewline,
}: ContextMenuProps) {
  const ref = useRef<HTMLDivElement>(null);
  useClickOutside(ref, true, onClose);

  const word = lyrics.words[wordIndex];
  const isSep = isSeparatorWord(word);
  const isSp = isSpaceWord(word);
  const isNl = isNewlineWord(word);
  const canSplit =
    !isSep && word.isReadingAutoGenerated && word.syllables.length === 1;

  const topActions = [
    { label: '编辑注音', disabled: isSep, action: () => onEditRuby(wordIndex) },
    { label: '编辑文字', disabled: false, action: () => onEditText(wordIndex) },
    { label: '拆分', disabled: !canSplit, action: () => onSplit(wordIndex) },
    { label: '删除', disabled: false, action: () => onDelete(wordIndex) },
  ];

  const convertActions: { label: string; action: () => void }[] = [];
  if (isSp) {
    convertActions.push(
      { label: '转化为换行', action: () => onConvertToNewline?.(wordIndex) },
      {
        label: '转化为文字',
        action: () => {
          onEditText(wordIndex);
          onClose();
        },
      },
    );
  } else if (isNl) {
    convertActions.push(
      { label: '转化为空格', action: () => onConvertToSpace?.(wordIndex) },
      {
        label: '转化为文字',
        action: () => {
          onEditText(wordIndex);
          onClose();
        },
      },
    );
  }

  const insertActions = [
    { label: '在前面插入卡片', action: () => onInsertBefore(wordIndex) },
    { label: '在后面插入卡片', action: () => onInsertAfter(wordIndex) },
    { label: '插入空格', action: () => onInsertSpace(wordIndex) },
    { label: '插入换行', action: () => onInsertNewline(wordIndex) },
  ];

  return (
    <div className="shared-ctx-menu" ref={ref} style={{ left: x, top: y }}>
      {topActions.map((item, i) => {
        if (!item.label) return <div key={i} className="shared-ctx-sep" />;
        return (
          <button
            key={item.label}
            type="button"
            className="shared-ctx-item"
            disabled={item.disabled}
            onClick={() => { item.action(); onClose(); }}
          >
            {item.label}
          </button>
        );
      })}
      {convertActions.length > 0 && <div className="shared-ctx-sep" />}
      {convertActions.map((item) => (
        <button
          key={item.label}
          type="button"
          className="shared-ctx-item"
          onClick={() => {
            item.action();
            onClose();
          }}
        >
          {item.label}
        </button>
      ))}
      <div className="shared-ctx-sep" />
      {insertActions.map((item) => (
        <button
          key={item.label}
          type="button"
          className="shared-ctx-item"
          onClick={() => {
            item.action();
            onClose();
          }}
        >
          {item.label}
        </button>
      ))}
    </div>
  );
}
