// jsondiffpatch is an ES module — use require() to work around
// CommonJS module system of this project.
const jsondiffpatch = require('jsondiffpatch');

import type { Lyrics } from '../editor/lyrics';
import { toJson } from '../editor/jsonlyrics';

type Delta = any;

export class UndoManager {
  /** Forward deltas: each delta = diff(prev_state, recorded_state) */
  private undoStack: Delta[] = [];
  /** Forward deltas stored when undoing, so redo can patch forward */
  private redoStack: Delta[] = [];
  /** JSON string of the most recently recorded state */
  private lastSnapshot: string | null = null;
  private maxSteps: number;

  constructor(maxSteps: number = 100) {
    this.maxSteps = maxSteps;
  }

  /**
   * Record the current lyrics state AFTER a mutation is complete.
   * Computes a diff from the previously recorded state and stores
   * only the delta instead of a full copy.
   */
  record(after: Lyrics): void {
    const currentJson = toJson(after);

    if (this.lastSnapshot) {
      const delta = jsondiffpatch.diff(
        JSON.parse(this.lastSnapshot),
        JSON.parse(currentJson),
      );
      if (delta && Object.keys(delta).length > 0) {
        this.undoStack.push(delta);
      }
    }

    this.lastSnapshot = currentJson;
    this.redoStack = [];

    while (this.undoStack.length > this.maxSteps) {
      this.undoStack.shift();
    }
  }

  canUndo(): boolean {
    return this.undoStack.length > 0;
  }

  canRedo(): boolean {
    return this.redoStack.length > 0;
  }

  undo(lyrics: Lyrics): boolean {
    const delta = this.undoStack.pop();
    if (!delta) return false;

    // Save forward delta for redo
    this.redoStack.push(delta);

    // Deep-copy current state, unpatch to go backward
    const currentObj = JSON.parse(toJson(lyrics));
    jsondiffpatch.unpatch(currentObj, delta);
    restoreFromObj(lyrics, currentObj);
    this.lastSnapshot = toJson(lyrics);
    return true;
  }

  redo(lyrics: Lyrics): boolean {
    const delta = this.redoStack.pop();
    if (!delta) return false;

    // Save forward delta for undo
    this.undoStack.push(delta);

    // Deep-copy current state, patch to go forward
    const currentObj = JSON.parse(toJson(lyrics));
    jsondiffpatch.patch(currentObj, delta);
    restoreFromObj(lyrics, currentObj);
    this.lastSnapshot = toJson(lyrics);
    return true;
  }

  clear(): void {
    this.undoStack = [];
    this.redoStack = [];
    this.lastSnapshot = null;
  }
}

function restoreFromObj(
  lyrics: Lyrics,
  obj: { words?: unknown[]; metadata?: Record<string, string> },
): void {
  const words = obj.words || [];
  const meta = obj.metadata || {};

  lyrics.words.length = 0;
  words.forEach((w: any) => {
    lyrics.words.push({
      reading: w.reading,
      syllables: (w.syllables || []).map((s: any) => ({
        reading: s.reading,
        isSet: s.isSet,
        time: { msec: s.time },
      })),
      withRuby: w.withRuby ?? false,
      isReadingAutoGenerated: w.isReadingAutoGenerated ?? true,
    });
  });

  Object.keys(meta).forEach((k) => {
    lyrics.metadata[k] = String(meta[k]);
  });
}
